import os
os.system("cls")
import time

print("Fernando: então alunos, quem ficou no top 5 já pode ir para casa")
print()
time.sleep(2.5)
print("Tailane: oxe oxe oxe, qual é professor? vale isso não")
print()
time.sleep(2.5)
print("Fernando: Vale sim, quem tiver no top 5 já pode ir embora, os restantes da sala vão ficar até 18:30 construindo uma bomba corrente elétrica pelo tinkercard, abre o site aí")
print()
time.sleep(2.5)
print("Tailane:vou ficar até 18 horas não prof, tenho trabalho")
print()
time.sleep(2.5)
print("Fernando: não é problema meu")
print()
time.sleep(2.5)
print("Bryan e Flávio se levantam e vão para casa; eles pegam um ônibus com ar-condicionado e chegam à estação em 30 minutos.")
print("Ao chegarem em casa, Flávio e Bryan, manhã seguinte os dois liga televisão pela tarde e ver a grande noticias")
time.sleep(2.5)
print()
print("ALO JUCA: Urgente uma garota do senai dendezeiro espanca o professor até que ele fique branco, rouba as motos e foge do local do crime")
print("ALO JUCA: A Polícia Está nas busca da garota")